name: selfdrive_tests

# Restored as a manual-only workflow to avoid unwanted CI runs.
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Acknowledge
        run: |
          echo "Workflow restored in this fork; CI disabled by default."
